'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class REGISTRO
    Public Property NOMBRE As String
    Public Property APELLIDO As String
    Public Property DIRECCCION As String
    Public Property TELEFONO As String
    Public Property SALARIO As Nullable(Of Integer)
    Public Property AREA As String
    Public Property FECHA_INGRESO As Nullable(Of Date)
    Public Property SEXO As String
    Public Property CODIGO As Nullable(Of Integer)
    Public Property JEFE As String
    Public Property TRABAJADOR_A_CARGO As String

End Class
